### PR TITLE
I fixed it

### PR DESCRIPTION
**Pull request by hilburn**

### CODE REVIEW

**Comment by jakimfett** [comment]
Before I accept this pull request I need you to [accept my CLA](https://github.com/jakimfett/MMPLv2/blob/master/LICENSE.md) which basically says you're giving me this code and I can do whatever the heck I want with it as long as I don't do Bad Things™.

Do you accept these terms?

**Comment by hilburn** [comment]
Yes, you have the right to use my boolean :P

**Comment by jakimfett** [comment]
Yay thanks

**Comment by way2muchnoise** [comment]
aaaand @hilburn just sold his soul to @jakimfett

**Comment by jakimfett** [comment]
In all fairness, that happened a long time ago, this was just formalizing it.

**Comment by jakimfett** [comment]
@hilburn almost...so close but not quite: 

It updates quantities, but not if different stacks are put in (testing two SMP players here).

I added another load craft grid call, and I think I've got it working...now I just need to figure out if it's sending excessive numbers of packets...

**Pull request merged**
